/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Classes.Reserva;
import Gerenciador.GerenciadorHospedes;
import Gerenciador.GerenciadorQuartos;
import Gerenciador.GerenciadorReservas;
import java.util.List;

/**
 *
 * @author 14626232639
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
        GerenciadorHospedes gerenciadorHospede = new GerenciadorHospedes();
        GerenciadorQuartos gerenciadorQuarto = new GerenciadorQuartos();
        GerenciadorReservas gerenciadorReserva = new GerenciadorReservas();
        
    public Home() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCadastroHospede = new javax.swing.JButton();
        btnCadastroQuarto = new javax.swing.JButton();
        btnRealizarReserva = new javax.swing.JButton();
        btnVisualizarReservas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        exibicaoDasReservas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("CADASTRO");
        jPanel1.add(jLabel1);

        btnCadastroHospede.setText("Hóspede");
        btnCadastroHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroHospedeActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastroHospede);

        btnCadastroQuarto.setText("Quarto");
        btnCadastroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroQuartoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastroQuarto);

        btnRealizarReserva.setText("Reservar");
        btnRealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarReservaActionPerformed(evt);
            }
        });
        jPanel2.add(btnRealizarReserva);

        btnVisualizarReservas.setText("Vizualizar reservas");
        btnVisualizarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarReservasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVisualizarReservas);

        exibicaoDasReservas.setColumns(20);
        exibicaoDasReservas.setRows(5);
        jScrollPane1.setViewportView(exibicaoDasReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroHospedeActionPerformed
        CadHospede novoHospede = new CadHospede(this, rootPaneCheckingEnabled);
        novoHospede.setVisible(true);
    }//GEN-LAST:event_btnCadastroHospedeActionPerformed

    private void btnCadastroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroQuartoActionPerformed
        CadQuarto novoQuarto = new CadQuarto(this, rootPaneCheckingEnabled);
        novoQuarto.setVisible(true);
    }//GEN-LAST:event_btnCadastroQuartoActionPerformed

    private void btnRealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarReservaActionPerformed
        RealizarReserva novaReserva = new RealizarReserva(this, rootPaneCheckingEnabled);
        novaReserva.setVisible(true);
    }//GEN-LAST:event_btnRealizarReservaActionPerformed

    private void btnVisualizarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarReservasActionPerformed
        List<Reserva> reservas = gerenciadorReserva.getReservas();
        String listagem = "";
        for(Reserva reserva : reservas){
            listagem = listagem + reserva.toString();
        }
        exibicaoDasReservas.setText(listagem);
    }//GEN-LAST:event_btnVisualizarReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroHospede;
    private javax.swing.JButton btnCadastroQuarto;
    private javax.swing.JButton btnRealizarReserva;
    private javax.swing.JButton btnVisualizarReservas;
    private javax.swing.JTextArea exibicaoDasReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
